services:
  allhands22:
    image: "${TESTING_IMAGE}"
  
  # postgres:
  #   image: postgres
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #   volumes:
  #     - ./healthchecks:/healthchecks
  #   healthcheck:
  #     test: /healthchecks/postgres-healthcheck
  #     interval: "5s"
  sut:
    image: "${TESTING_IMAGE}"
    depends_on:
      allhands22:
        condition: service_started
      # postgres:
      #   condition: service_healthy
    # run all your tests here against the allhands22 service
    command: |
      if [ $(curl http://allhands22:5000 | grep 'MLflow' | wc -l) -gt 0 ]; then
        exit 0
      else
        exit 1
      fi